import { createHash } from "node:crypto";
import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { gunzipSync } from "node:zlib";

export type Cell = string | number | boolean | null;
export type Row = Record<string, Cell>;

/** Downloads `url` once into `cacheDir`; later runs reuse the cached copy. */
export async function cachedDownload(
  url: string,
  cacheDir: string,
  name = path.basename(new URL(url).pathname)
) {
  mkdirSync(cacheDir, { recursive: true });
  const file = path.join(cacheDir, name);
  if (!existsSync(file)) {
    const response = await fetch(url);
    if (!response.ok) {
      throw new Error(`${url}: ${response.status} ${response.statusText}`);
    }
    writeFileSync(file, Buffer.from(await response.arrayBuffer()));
  }
  return file;
}

export function sha256(file: string | Buffer) {
  const bytes = typeof file === "string" ? readFileSync(file) : file;
  return createHash("sha256").update(bytes).digest("hex");
}

function csvCell(value: Cell) {
  if (
    value === null ||
    (typeof value === "number" && !Number.isFinite(value))
  ) {
    return "";
  }
  const text = String(value);
  return /[",\n\r]/.test(text) ? `"${text.replace(/"/g, '""')}"` : text;
}

/** Writes rows as CSV with the given column order; returns the file's facts. */
export function writeCsv(file: string, columns: string[], rows: Row[]) {
  mkdirSync(path.dirname(file), { recursive: true });
  const lines = [columns.map(csvCell).join(",")];
  for (const row of rows) {
    lines.push(columns.map((column) => csvCell(row[column] ?? null)).join(","));
  }
  const bytes = Buffer.from(`${lines.join("\n")}\n`);
  writeFileSync(file, bytes);
  return {
    file: path.basename(file),
    rows: rows.length,
    columns,
    bytes: bytes.length,
    sha256: sha256(bytes),
  };
}

/**
 * Writes the audited counts and findings an analysis quotes as a TypeScript
 * module beside the demo's analysis definitions, so copy and data agree.
 */
export function writeFacts(name: string, facts: unknown) {
  const root = path.resolve(import.meta.dirname, "../../..");
  const file = path.join(
    root,
    "apps/demo/src/demos/analyses/facts",
    `${name}.ts`
  );
  mkdirSync(path.dirname(file), { recursive: true });
  writeFileSync(
    file,
    `// Generated by apps/data-samples/prepare/${name}.ts. Do not edit.\n` +
      `export const facts = ${JSON.stringify(facts, null, 2)} as const;\n`
  );
}

/** Parses a CSV with a header row. Quoted fields may hold commas and quotes. */
export function readCsv(
  text: string,
  delimiter = ","
): Record<string, string>[] {
  const records: string[][] = [];
  let field = "";
  let record: string[] = [];
  let quoted = false;
  for (let index = 0; index < text.length; index++) {
    const char = text[index]!;
    if (quoted) {
      if (char === '"' && text[index + 1] === '"') {
        field += '"';
        index++;
      } else if (char === '"') {
        quoted = false;
      } else {
        field += char;
      }
    } else if (char === '"') {
      quoted = true;
    } else if (char === delimiter) {
      record.push(field);
      field = "";
    } else if (char === "\n" || char === "\r") {
      if (char === "\r" && text[index + 1] === "\n") {
        index++;
      }
      record.push(field);
      records.push(record);
      record = [];
      field = "";
    } else {
      field += char;
    }
  }
  if (field !== "" || record.length) {
    record.push(field);
    records.push(record);
  }
  const [header, ...body] = records.filter(
    (item) => item.length > 1 || item[0] !== ""
  );
  return body.map((values) =>
    Object.fromEntries(
      header!.map((name, index) => [name, values[index] ?? ""])
    )
  );
}

// ---------------------------------------------------------------------------
// A reader for the R data frames in an .rda file (XDR serialization, gzip or
// bzip2). It handles the vector types data frames use and nothing more.

const NA_INTEGER = -2147483648;

type RValue =
  | null
  | { type: "symbol"; name: string }
  | { type: "vector"; values: unknown[]; attributes: Map<string, RValue> }
  | { type: "pairlist"; items: Array<{ tag?: string; value: RValue }> };

class XdrReader {
  offset = 0;
  private refs: RValue[] = [];
  private bytes: Buffer;
  constructor(bytes: Buffer) {
    this.bytes = bytes;
  }

  int() {
    const value = this.bytes.readInt32BE(this.offset);
    this.offset += 4;
    return value;
  }

  double() {
    const value = this.bytes.readDoubleBE(this.offset);
    // R's NA_real_ is a NaN whose low word is 1954.
    const low = this.bytes.readUInt32BE(this.offset + 4);
    this.offset += 8;
    return Number.isNaN(value) && low === 1954 ? null : value;
  }

  string(length: number) {
    const text = this.bytes.toString("utf8", this.offset, this.offset + length);
    this.offset += length;
    return text;
  }

  item(): RValue {
    const flags = this.int();
    const type = flags & 0xff;
    const hasAttributes = (flags & (1 << 9)) !== 0;
    const hasTag = (flags & (1 << 10)) !== 0;
    switch (type) {
      case 254: // NILVALUE_SXP
      case 242: // EMPTYENV_SXP
      case 241: // BASEENV_SXP
      case 253: // GLOBALENV_SXP
        return null;
      case 255: {
        // REFSXP
        const index = flags >> 8 || this.int();
        return this.refs[index - 1] ?? null;
      }
      case 1: {
        // SYMSXP
        const name = this.item() as unknown as string;
        const symbol = { type: "symbol" as const, name };
        this.refs.push(symbol);
        return symbol;
      }
      case 2: {
        // LISTSXP
        const items: Array<{ tag?: string; value: RValue }> = [];
        let current = flags;
        for (;;) {
          if ((current & (1 << 9)) !== 0) {
            this.item();
          }
          const tag =
            (current & (1 << 10)) !== 0
              ? (this.item() as { name: string } | null)?.name
              : undefined;
          items.push({ tag, value: this.item() });
          current = this.int();
          if ((current & 0xff) !== 2) {
            break;
          }
        }
        // The list ends with NILVALUE_SXP, already read as `current`.
        return { type: "pairlist", items };
      }
      case 9: {
        // CHARSXP: returned as a bare string to its parent.
        const length = this.int();
        return (length === -1
          ? null
          : this.string(length)) as unknown as RValue;
      }
      case 10:
      case 13: {
        const length = this.int();
        const values = Array.from({ length }, () => {
          const value = this.int();
          return value === NA_INTEGER ? null : value;
        });
        return this.withAttributes(values, hasAttributes);
      }
      case 14: {
        const length = this.int();
        const values = Array.from({ length }, () => this.double());
        return this.withAttributes(values, hasAttributes);
      }
      case 16: {
        const length = this.int();
        const values = Array.from({ length }, () => this.item());
        return this.withAttributes(values, hasAttributes);
      }
      case 19: {
        const length = this.int();
        const values = Array.from({ length }, () => this.item());
        return this.withAttributes(values, hasAttributes);
      }
      default:
        throw new Error(
          `Unsupported R type ${type} at byte ${this.offset}${hasTag ? " (tagged)" : ""}`
        );
    }
  }

  private withAttributes(values: unknown[], hasAttributes: boolean): RValue {
    const attributes = new Map<string, RValue>();
    if (hasAttributes) {
      const list = this.item();
      if (list && list.type === "pairlist") {
        for (const { tag, value } of list.items) {
          if (tag) attributes.set(tag, value);
        }
      }
    }
    return { type: "vector", values, attributes };
  }
}

function decompress(file: string) {
  const bytes = readFileSync(file);
  if (bytes[0] === 0x1f && bytes[1] === 0x8b) return gunzipSync(bytes);
  if (bytes.toString("latin1", 0, 3) === "BZh") {
    return execFileSync("bzip2", ["-dc", file], { maxBuffer: 1 << 30 });
  }
  return bytes;
}

/**
 * Reads the data frame in an .rda file as rows. Factors become their labels;
 * NA becomes null. POSIXct columns stay as seconds since the epoch.
 */
export function readRdaFrame(file: string): { name: string; rows: Row[] } {
  const bytes = decompress(file);
  if (
    bytes.toString("latin1", 0, 5) !== "RDX2\n" &&
    bytes.toString("latin1", 0, 5) !== "RDX3\n"
  ) {
    throw new Error(`${file} is not an R data file`);
  }
  const reader = new XdrReader(bytes);
  reader.offset = 5;
  if (reader.string(2) !== "X\n")
    throw new Error("Only XDR files are supported");
  const version = reader.int();
  reader.int();
  reader.int();
  if (version === 3) reader.string(reader.int());
  const top = reader.item();
  if (!top || top.type !== "pairlist" || !top.items[0]) {
    throw new Error(`${file} holds no object`);
  }
  const { tag, value: frame } = top.items[0];
  if (!frame || frame.type !== "vector") throw new Error("Not a data frame");
  const names = (frame.attributes.get("names") as { values: string[] }).values;
  const columns = frame.values.map((column) => {
    const vector = column as Extract<RValue, { type: "vector" }>;
    const levels = vector.attributes.get("levels") as
      | { values: string[] }
      | undefined;
    return levels
      ? vector.values.map((code) =>
          code === null ? null : levels.values[(code as number) - 1]!
        )
      : vector.values;
  });
  const length = columns[0]?.length ?? 0;
  const rows: Row[] = Array.from({ length }, (_, index) =>
    Object.fromEntries(
      names.map((name, column) => [name, columns[column]![index] as Cell])
    )
  );
  return { name: tag ?? path.basename(file, ".rda"), rows };
}
