export function MethodHelp() {
  return <details className="sl-readouts"><summary>Method definitions, assumptions and limitations</summary>
    <div className="sl-help-grid">
      <section><h3>Rows and coordinates</h3><p>Analysis defaults to finite X/Y pairs passing every active filter in the active facet. Gray context points are not silently fitted. The reference population estimates centers and sample covariance; the scoring population receives distances. Full-source and training references ignore selection and facet changes. Grouped models never borrow a different group's covariance.</p><p>Blank strings, booleans, missing and nonfinite values are not measurements. Finite numeric strings are accepted. Source IDs survive all computations. Display domains use every finite source value, independently by axis, padded 10% in display coordinates; filters and facets do not change them. A categorical axis disables numeric methods rather than fitting jitter.</p></section>
      <section><h3>Hexagonal bins</h3><p>Pointy-top hexagons have radius r in CSS plot pixels. Axial center (q,k) is (√3·r·(q+k/2), 3·r·k/2); the origin is the top-left plot corner. A point belongs to the nearest center; exact ties prefer smaller q then smaller k. Inspection lists exact IDs and never substitutes a rectangular filter. On resize both panels use the same new plot size, so pixel bins are recalculated. The legend means rows per bin, not density.</p></section>
      <section><h3>Two-dimensional kernel density</h3><p>A Gaussian kernel is approximated by bilinear deposition on a 4-pixel grid and separable Gaussian convolution. Bandwidth is the kernel's standard deviation in CSS plot pixels. The kernel is truncated at ±4 bandwidths on each axis and discretely normalized. An expanded grid retains edge tails; the viewport clips the display but does not renormalize the visible region.</p><p>Each row contributes unit mass, so the padded-grid integral is the analysis count. Units are rows per square plot pixel; there is no probability-density mode or physical-unit density claim. Contours are linearly spaced intensity thresholds on a shared full-source scale, not probability-mass regions. Density and bins remain pooled when covariance models are grouped. No group is normalized to its own mass.</p></section>
      <section><h3>Covariance and distance</h3><p>The sample covariance matrix uses paired finite observations and denominator n−1. Diagonal entries have squared field units; the cross term has X-unit·Y-unit. Pearson correlation is dimensionless. Mahalanobis squared distance is D²=(z−mean)ᵀS⁻¹(z−mean); D=√D². Both depend on the declared reference estimate, not point opacity.</p><p>Zero variance, fewer than two pairs, overflow, and a standardized covariance eigenvalue ratio at or below 1e−10 are explicit unavailable results. No ridge or pseudoinverse is substituted. Distant rows can be valid observations, mixtures or model mismatches. Ordinary sample covariance is sensitive to contamination.</p></section>
      <section><h3>Two different ellipse meanings</h3><p>A <b>data ellipse</b> uses q=−2 ln(1−a); its semiaxes are √(qλ). At 95% fitted Gaussian coverage, q≈5.991464547 and the distance radius is ≈2.447746831. It is not an exact finite-sample outlier test and does not use the one-dimensional 1.96 multiplier.</p><p>A <b>confidence region for the mean</b> uses q=[2(n−1)/(n−2)]·F(2,n−2;a)/n. This is Hotelling's finite-sample result for independent bivariate normal observations, n&gt;2 and full-rank covariance. Its coverage concerns the unknown population mean, not observations. Repeated-sampling validation and quantile checks are recorded in the report. Prediction regions for future observations and statistical tolerance regions are deferred.</p><p>Boundary vertices are sampled in the analysis coordinates, then mapped through the display scales. A data-space ellipse displayed on symlog axes need not look elliptical. A transformed-coordinate analysis is a different model and recomputes every moment and distance.</p></section>
      <section><h3>Principal axes and marginals</h3><p>Principal axes are eigenvectors of sample covariance, not standardized correlation. Each line extends one √λ from the mean in each direction. Eigenvalues describe variance along the axes in the chosen numeric-coordinate metric. Covariance PCA with unequal field units is unit-sensitive; changing units can rotate the result and change variance shares.</p><p>Both marginal histograms count the same eligible X/Y pairs as the analysis, not separately available X-only or Y-only rows. Bins are equal-width in analysis coordinates with common full-source domains; intervals are left-closed/right-open except the final maximum is included.</p></section>
    </div>
    <p className="sl-muted">Statistical references: <a href="https://www.itl.nist.gov/div898/handbook/pmc/section5/pmc543.htm" target="_blank" rel="noreferrer">NIST Hotelling T²</a> · <a href="https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.f.html" target="_blank" rel="noreferrer">SciPy F quantiles</a> · <a href="https://d3js.org/d3-contour/density" target="_blank" rel="noreferrer">D3's count-intensity interpretation</a>. Geometry and density here are local deterministic implementations, not D3 estimator calls.</p>
  </details>;
}
