import { SavedDataStructure } from "exploreda";

const axes = {
  xAxis: { scaleType: "linear", grid: false, min: 0, max: 100 },
  yAxis: { scaleType: "linear", grid: false, min: 0, max: 100 },
} as const;
const noFacet = {
  enabled: false,
  type: "wrap",
  rowVariable: "",
  columnCount: 2,
} as const;
const moodScaleId = "0867bff2-86d3-48ff-9ef4-353575e0b156";

export const boxPlotSettings: SavedDataStructure = {
  charts: [
    {
      title: "What does each day record?",
      type: "summary",
      field: "",
      layout: { x: 0, y: 0, w: 5, h: 6 },
      ...axes,
      margin: { top: 5, right: 5, bottom: 5, left: 5 },
      facet: noFacet,
      xAxisLabel: "",
      yAxisLabel: "",
      xGridLines: 5,
      yGridLines: 5,
      filters: [],
      id: "2d71ef50-9f8f-4435-8577-99d84a24e28e",
      colorScaleId: undefined,
      colorField: undefined,
    },
    {
      title: "Do hotter days sell more ice cream?",
      type: "scatter",
      field: "",
      layout: { x: 5, y: 0, w: 7, h: 4 },
      ...axes,
      margin: { top: 20, right: 20, bottom: 45, left: 60 },
      facet: noFacet,
      colorScaleId: moodScaleId,
      colorField: "Mood Index",
      xAxisLabel: "Temperature (°C)",
      yAxisLabel: "Ice cream sales",
      xGridLines: 5,
      yGridLines: 5,
      filters: [],
      id: "6f0c1f0e-6a52-4a7e-9e57-5f3f0f5b7a11",
      xField: "Temperature (°C)",
      yField: "Ice Cream Sales",
    },
    {
      id: "0b8a3f5e-2c1d-4d9b-8f6e-3a7c9d2e4b15",
      type: "color-legend",
      title: "Mood Index color key",
      field: "",
      layout: { x: 5, y: 4, w: 7, h: 1 },
      facet: {
        enabled: false,
        type: "grid",
        rowVariable: "",
        columnVariable: "",
      },
      ...axes,
      colorField: undefined,
      margin: { top: 20, right: 20, bottom: 20, left: 20 },
      filters: [],
      xAxisLabel: "",
      yAxisLabel: "",
      xGridLines: 0,
      yGridLines: 0,
      fields: ["Mood Index"],
      colorScaleId: moodScaleId,
      numericalBreakpoints: 5,
      wrap: false,
    },
    {
      title: "How warm are the days at each mood level?",
      type: "boxplot",
      field: "Temperature (°C)",
      layout: { x: 5, y: 5, w: 7, h: 4 },
      ...axes,
      margin: { top: 20, right: 20, bottom: 30, left: 60 },
      facet: noFacet,
      colorScaleId: moodScaleId,
      colorField: "Mood Index",
      xAxisLabel: "Mood Index",
      yAxisLabel: "Temperature (°C)",
      xGridLines: 5,
      yGridLines: 5,
      filters: [],
      id: "384f8bd5-0c6f-4997-86ef-822749431aff",
      whiskerType: "tukey",
      showOutliers: true,
      violinOverlay: true,
      sortBy: "median",
      violinBandwidth: 0.3,
      autoBandwidth: true,
      styles: {
        boxFill: "hsl(217.2 91.2% 59.8%)",
        boxStroke: "black",
        boxStrokeWidth: 1,
        medianStroke: "white",
        medianStrokeWidth: 2,
        whiskerStroke: "black",
        whiskerStrokeWidth: 1,
        outlierSize: 3,
        outlierStroke: "black",
        outlierFill: "none",
      },
    },
    {
      title: "Brush productivity scores",
      type: "bar",
      field: "Productivity Score",
      layout: { x: 0, y: 6, w: 5, h: 3 },
      ...axes,
      margin: { top: 20, right: 20, bottom: 45, left: 50 },
      facet: noFacet,
      xAxisLabel: "Productivity score",
      yAxisLabel: "Days",
      xGridLines: 5,
      yGridLines: 5,
      filters: [],
      id: "9c1e5d2a-7b3f-4e8a-a6d4-1f2b3c4d5e6f",
      colorScaleId: undefined,
      colorField: undefined,
      binCount: 20,
    },
  ],
  calculations: [],
  gridSettings: {
    columnCount: 12,
    rowHeight: 100,
    containerPadding: 10,
    showBackgroundMarkers: true,
  },
  metadata: {
    name: "Weather and mood",
    version: 1,
    createdAt: "2025-03-21T03:34:35.533Z",
    modifiedAt: "2026-09-28T00:00:00.000Z",
  },
  colorScales: [
    {
      name: "Mood Index",
      sourceField: "Mood Index",
      type: "numerical",
      palette: "Viridis",
      min: 1,
      max: 10,
      id: moodScaleId,
    },
  ],
};
