import { SavedDataStructure } from "exploreda";

export const categoricalChartSettings: SavedDataStructure = {
  charts: [
    {
      title: "Row Chart: ",
      type: "row",
      field: "Category",
      layout: { x: 7, y: 0, w: 5, h: 4 },
      xAxis: { scaleType: "linear", grid: false, min: 0, max: 100 },
      yAxis: { scaleType: "linear", grid: false, min: 0, max: 100 },
      margin: { top: 20, right: 20, bottom: 20, left: 20 },
      facet: {
        enabled: false,
        type: "wrap",
        rowVariable: "",
        columnCount: 2,
      },
      xAxisLabel: "",
      yAxisLabel: "",
      xGridLines: 5,
      yGridLines: 5,
      minRowHeight: 30,
      maxRowHeight: 50,
      filters: [],
      id: "2437c0f2-6ad0-4b1d-a47b-445ab15056b1",
      colorScaleId: "ffca7163-a613-40fe-9a1c-a85e6bdc37b9",
      colorField: "Category",
    },
    {
      title: "Pivot Table",
      type: "pivot",
      field: "",
      layout: { x: 0, y: 0, w: 7, h: 5 },
      xAxis: { scaleType: "linear", grid: false, min: 0, max: 100 },
      yAxis: { scaleType: "linear", grid: false, min: 0, max: 100 },
      margin: { top: 20, right: 20, bottom: 20, left: 20 },
      facet: {
        enabled: false,
        type: "wrap",
        rowVariable: "",
        columnCount: 2,
      },
      xAxisLabel: "",
      yAxisLabel: "",
      xGridLines: 5,
      yGridLines: 5,
      rowFields: ["Category", "Subcategory"],
      columnField: "Rating",
      valueFields: [{ field: "Category", aggregation: "count" }],
      showTotals: { row: false, column: false, grand: false },
      filters: [],
      id: "7a345418-85b6-42d7-a86d-018cefe74d6e",
    },
    {
      title: "Row Chart: ",
      type: "row",
      field: "Material",
      layout: { x: 3, y: 5, w: 9, h: 8 },
      xAxis: { scaleType: "linear", grid: false, min: 0, max: 100 },
      yAxis: { scaleType: "linear", grid: false, min: 0, max: 100 },
      margin: { top: 20, right: 20, bottom: 20, left: 20 },
      facet: {
        enabled: true,
        type: "grid",
        rowVariable: "In Stock",
        columnCount: 2,
        columnVariable: "Size",
      },
      xAxisLabel: "",
      yAxisLabel: "",
      xGridLines: 5,
      yGridLines: 5,
      minRowHeight: 30,
      maxRowHeight: 30,
      filters: [],
      id: "270bde24-5470-4f8b-8b74-f6e035279ce8",
      binCount: 10,
      forceString: false,
    },
  ],
  calculations: [],
  gridSettings: {
    columnCount: 12,
    rowHeight: 100,
    containerPadding: 10,
    showBackgroundMarkers: true,
  },
  metadata: {
    name: "Untitled",
    version: 1,
    createdAt: "2025-03-05T04:51:43.917Z",
    modifiedAt: "2025-03-05T04:51:43.917Z",
  },
  colorScales: [
    {
      name: "Category",
      type: "categorical",
      palette: ["#1f77b4", "#ff7f0e", "#2ca02c", "#d62728", "#9467bd"],
      mapping: [
        ["Food", "#1f77b4"],
        ["Home", "#ff7f0e"],
        ["Electronics", "#2ca02c"],
        ["Sports", "#d62728"],
        ["Clothing", "#9467bd"],
      ],
      id: "ffca7163-a613-40fe-9a1c-a85e6bdc37b9",
    },
  ],
};
