import { SavedDataStructure } from "exploreda";

export const categoricalSmallSettings: SavedDataStructure = {
  charts: [
    {
      title: "Data Summary",
      type: "summary",
      field: "",
      layout: { x: 0, y: 0, w: 6, h: 6 },
      xAxis: { scaleType: "linear", grid: false, min: 0, max: 100 },
      yAxis: { scaleType: "linear", grid: false, min: 0, max: 100 },
      margin: { top: 20, right: 20, bottom: 20, left: 20 },
      colorScaleId: undefined,
      colorField: undefined,
      facet: {
        enabled: false,
        type: "wrap",
        rowVariable: "",
        columnCount: 2,
      },
      xAxisLabel: "",
      yAxisLabel: "",
      xGridLines: 5,
      yGridLines: 5,
      filters: [],
      id: "a4a09ac0-43bb-4c46-bd25-5ca0b1fd6a56",
    },
    {
      title: "Data Table",
      type: "data-table",
      field: "",
      layout: { x: 6, y: 0, w: 6, h: 5 },
      xAxis: { scaleType: "linear", grid: false, min: 0, max: 100 },
      yAxis: { scaleType: "linear", grid: false, min: 0, max: 100 },
      margin: { top: 20, right: 20, bottom: 20, left: 20 },
      colorScaleId: undefined,
      colorField: undefined,
      facet: {
        enabled: false,
        type: "wrap",
        rowVariable: "",
        columnCount: 2,
      },
      xAxisLabel: "",
      yAxisLabel: "",
      xGridLines: 5,
      yGridLines: 5,
      columns: [
        { id: "Category", field: "Category", width: 50 },
        { id: "ID", field: "ID", width: 50 },
        {
          id: "Subcategory",
          field: "Subcategory",
          width: 180,
        },
      ],
      pageSize: 10,
      currentPage: 1,
      filters: [],
      id: "0ecad4f5-288f-48a3-8ae2-942d24780120",
      sortDirection: "asc",
      sortBy: "ID",
      globalSearch: "",
      tableHeight: 400,
    },
  ],
  calculations: [],
  gridSettings: {
    columnCount: 12,
    rowHeight: 100,
    containerPadding: 10,
    showBackgroundMarkers: true,
  },
  metadata: {
    name: "Untitled",
    version: 1,
    createdAt: "2025-03-06T03:37:47.839Z",
    modifiedAt: "2025-03-06T03:37:47.840Z",
  },
  colorScales: [],
};
