import { SavedDataStructure } from "exploreda";

export const colorLegendSettings: SavedDataStructure = {
  charts: [
    {
      title: "Row Chart: ",
      type: "row",
      field: "Category",
      layout: { x: 7, y: 4, w: 5, h: 4 },
      xAxis: { scaleType: "linear", grid: false, min: 0, max: 100 },
      yAxis: { scaleType: "linear", grid: false, min: 0, max: 100 },
      margin: { top: 20, right: 20, bottom: 20, left: 20 },
      facet: { enabled: false, type: "wrap", rowVariable: "", columnCount: 2 },
      xAxisLabel: "",
      yAxisLabel: "",
      xGridLines: 5,
      yGridLines: 5,
      minRowHeight: 30,
      maxRowHeight: 50,
      filters: [],
      id: "2437c0f2-6ad0-4b1d-a47b-445ab15056b1",
      colorScaleId: "ffca7163-a613-40fe-9a1c-a85e6bdc37b9",
      colorField: "Category",
    },
    {
      title: "Pivot Table",
      type: "pivot",
      field: "",
      layout: { x: 0, y: 4, w: 7, h: 5 },
      xAxis: { scaleType: "linear", grid: false, min: 0, max: 100 },
      yAxis: { scaleType: "linear", grid: false, min: 0, max: 100 },
      margin: { top: 20, right: 20, bottom: 20, left: 20 },
      facet: { enabled: false, type: "wrap", rowVariable: "", columnCount: 2 },
      xAxisLabel: "",
      yAxisLabel: "",
      xGridLines: 5,
      yGridLines: 5,
      rowFields: ["Category", "Subcategory"],
      columnField: "Rating",
      valueFields: [{ field: "Category", aggregation: "count" }],
      showTotals: { row: false, column: false, grand: false },
      filters: [],
      id: "7a345418-85b6-42d7-a86d-018cefe74d6e",
    },
    {
      title: "Row Chart: ",
      type: "row",
      field: "Material",
      layout: { x: 3, y: 9, w: 9, h: 8 },
      xAxis: { scaleType: "linear", grid: false, min: 0, max: 100 },
      yAxis: { scaleType: "linear", grid: false, min: 0, max: 100 },
      margin: { top: 20, right: 20, bottom: 20, left: 20 },
      facet: {
        enabled: true,
        type: "grid",
        rowVariable: "In Stock",
        columnCount: 2,
        columnVariable: "Size",
      },
      xAxisLabel: "",
      yAxisLabel: "",
      xGridLines: 5,
      yGridLines: 5,
      minRowHeight: 30,
      maxRowHeight: 30,
      filters: [],
      id: "270bde24-5470-4f8b-8b74-f6e035279ce8",
      binCount: 10,
      forceString: false,
    },
    {
      id: "d68f2b1b-e4bc-466d-8228-9d7e2edbb5ed",
      type: "color-legend",
      title: "Color Legend",
      field: "",
      layout: { x: 6, y: 0, w: 6, h: 4 },
      facet: {
        enabled: false,
        type: "grid",
        rowVariable: "",
        columnCount: 2,
        columnVariable: "",
      },
      xAxis: { scaleType: "linear", grid: false, min: 0, max: 100 },
      yAxis: { scaleType: "linear", grid: false, min: 0, max: 100 },
      margin: { top: 20, right: 20, bottom: 20, left: 20 },
      filters: [],
      xAxisLabel: "",
      yAxisLabel: "",
      xGridLines: 0,
      yGridLines: 0,
      showTitle: false,
      showSearch: false,
      compact: false,
      fields: ["Category", "Rating"],
    },
    {
      title: "Bar Chart",
      type: "bar",
      field: "Rating",
      layout: { x: 0, y: 0, w: 6, h: 4 },
      xAxis: { scaleType: "linear", grid: false, min: 0, max: 100 },
      yAxis: { scaleType: "linear", grid: false, min: 0, max: 100 },
      margin: { top: 20, right: 20, bottom: 20, left: 20 },
      facet: { enabled: false, type: "wrap", rowVariable: "", columnCount: 2 },
      colorScaleId: "c1b1b4c2-bf98-4c4c-9752-1327cb089c8f",
      colorField: "Rating",
      xAxisLabel: "",
      yAxisLabel: "",
      xGridLines: 5,
      yGridLines: 5,
      filters: [],
      id: "009b2b69-ead4-479b-81e6-8add004a63d0",
      binCount: 10,
    },
  ],
  calculations: [],
  gridSettings: {
    columnCount: 12,
    rowHeight: 100,
    containerPadding: 10,
    showBackgroundMarkers: true,
  },
  metadata: {
    name: "Untitled",
    version: 1,
    createdAt: "2025-03-10T03:20:12.150Z",
    modifiedAt: "2025-03-10T03:20:12.150Z",
  },
  colorScales: [
    {
      name: "Category",
      type: "categorical",
      palette: ["#1f77b4", "#ff7f0e", "#2ca02c", "#d62728", "#9467bd"],
      mapping: [
        ["Food", "#1f77b4"],
        ["Home", "#ff7f0e"],
        ["Electronics", "#2ca02c"],
        ["Sports", "#d62728"],
        ["Clothing", "#9467bd"],
      ],
      id: "ffca7163-a613-40fe-9a1c-a85e6bdc37b9",
    },
    {
      name: "Rating",
      type: "numerical",
      palette: "Viridis",
      min: 1,
      max: 5,
      id: "c1b1b4c2-bf98-4c4c-9752-1327cb089c8f",
    },
  ],
};
