import { SavedDataStructure } from "exploreda";

export const fifaSettings: SavedDataStructure = {
  charts: [
    {
      title: "",
      type: "row",
      field: "nation",
      layout: { x: 6, y: 0, w: 6, h: 4 },
      xAxis: { scaleType: "linear", grid: false, min: 0, max: 100 },
      yAxis: { scaleType: "linear", grid: false, min: 0, max: 100 },
      margin: { top: 20, right: 20, bottom: 20, left: 20 },
      facet: { enabled: false, type: "wrap", rowVariable: "", columnCount: 2 },
      colorScaleId: "9295a070-ddd9-4faf-acab-33ef254de5ac",
      colorField: "nation",
      xAxisLabel: "",
      yAxisLabel: "",
      xGridLines: 5,
      yGridLines: 5,
      filters: [],
      minRowHeight: 30,
      maxRowHeight: 50,
      id: "18056a73-340f-48b2-a1e5-f462b7dc5438",
    },
    {
      title: "Summary Table",
      type: "summary",
      field: "",
      layout: { x: 0, y: 0, w: 6, h: 9 },
      xAxis: { scaleType: "linear", grid: false, min: 0, max: 100 },
      yAxis: { scaleType: "linear", grid: false, min: 0, max: 100 },
      margin: { top: 20, right: 20, bottom: 20, left: 20 },
      colorScaleId: undefined,
      colorField: undefined,
      facet: { enabled: false, type: "wrap", rowVariable: "", columnCount: 2 },
      xAxisLabel: "",
      yAxisLabel: "",
      xGridLines: 5,
      yGridLines: 5,
      filters: [],
      id: "45e372c9-e917-4bdb-b28a-c39811764176",
    },
    {
      title: "Pivot Table",
      type: "pivot",
      field: "",
      layout: { x: 6, y: 4, w: 6, h: 4 },
      xAxis: { scaleType: "linear", grid: false, min: 0, max: 100 },
      yAxis: { scaleType: "linear", grid: false, min: 0, max: 100 },
      colorScaleId: undefined,
      colorField: undefined,
      margin: { top: 20, right: 20, bottom: 20, left: 20 },
      facet: { enabled: false, type: "wrap", rowVariable: "", columnCount: 2 },
      xAxisLabel: "",
      yAxisLabel: "",
      xGridLines: 5,
      yGridLines: 5,
      filters: [],
      id: "e4551c07-9a3f-4652-a9e6-ed551ffefc38",
      rowFields: ["nation", "position"],
      columnField: "",
      valueFields: [{ field: "", aggregation: "count" }],
      showTotals: { row: true, column: true, grand: true },
    },
  ],
  calculations: [],
  gridSettings: {
    columnCount: 12,
    rowHeight: 100,
    containerPadding: 10,
    showBackgroundMarkers: true,
  },
  metadata: {
    name: "Untitled",
    version: 1,
    createdAt: "2025-03-12T03:34:02.083Z",
    modifiedAt: "2025-03-12T03:34:02.083Z",
  },
  colorScales: [
    {
      name: "nation",
      type: "categorical",
      palette: [
        "#1f77b4",
        "#ff7f0e",
        "#2ca02c",
        "#d62728",
        "#9467bd",
        "#8c564b",
        "#e377c2",
        "#7f7f7f",
        "#bcbd22",
        "#17becf",
        "#1f77b4",
        "#ff7f0e",
        "#2ca02c",
        "#d62728",
        "#9467bd",
        "#8c564b",
        "#e377c2",
        "#7f7f7f",
        "#bcbd22",
        "#17becf",
        "#1f77b4",
        "#ff7f0e",
        "#2ca02c",
        "#d62728",
        "#9467bd",
        "#8c564b",
        "#e377c2",
        "#7f7f7f",
        "#bcbd22",
      ],
      mapping: [
        ["France", "#1f77b4"],
        ["Spain", "#ff7f0e"],
        ["Norway", "#2ca02c"],
        ["Belgium", "#d62728"],
        ["Argentina", "#9467bd"],
        ["Australia", "#8c564b"],
        ["England", "#e377c2"],
        ["Poland", "#7f7f7f"],
        ["Egypt", "#bcbd22"],
        ["Portugal", "#17becf"],
        ["Brazil", "#1f77b4"],
        ["United States", "#ff7f0e"],
        ["Germany", "#2ca02c"],
        ["Holland", "#d62728"],
        ["Nigeria", "#9467bd"],
        ["Uruguay", "#8c564b"],
        ["Slovenia", "#e377c2"],
        ["Chile", "#7f7f7f"],
        ["Sweden", "#bcbd22"],
        ["Croatia", "#17becf"],
        ["Switzerland", "#1f77b4"],
        ["Korea Republic", "#ff7f0e"],
        ["Italy", "#2ca02c"],
        ["Algeria", "#d62728"],
        ["Serbia", "#9467bd"],
        ["Georgia", "#8c564b"],
        ["Scotland", "#e377c2"],
        ["Senegal", "#7f7f7f"],
        ["Canada", "#bcbd22"],
      ],
      id: "9295a070-ddd9-4faf-acab-33ef254de5ac",
    },
  ],
};
