import { SavedDataStructure } from "exploreda";

export const lineChartSettings: SavedDataStructure = {
  charts: [
    {
      title: "What ranges define this dataset?",
      type: "summary",
      field: "",
      layout: { x: 8, y: 0, w: 4, h: 6 },
      xAxis: { scaleType: "linear", grid: false, min: 0, max: 100 },
      yAxis: { scaleType: "linear", grid: false, min: 0, max: 100 },
      colorScaleId: undefined,
      colorField: undefined,
      margin: { top: 20, right: 20, bottom: 20, left: 20 },
      facet: { enabled: false, type: "wrap", rowVariable: "", columnCount: 2 },
      xAxisLabel: "",
      yAxisLabel: "",
      xGridLines: 5,
      yGridLines: 5,
      filters: [],
      id: "9c8a9f83-916a-4beb-910a-902b58cfe5d8",
    },
    {
      id: "22b47715-2956-4f55-9274-224d3835eff4",
      type: "line",
      title: "How does square-root growth slow as ID increases?",
      field: "",
      layout: { x: 0, y: 0, w: 8, h: 5 },
      facet: {
        enabled: false,
        type: "grid",
        rowVariable: "",
        columnVariable: "",
      },
      xAxis: { scaleType: "linear", grid: false, min: 0, max: 100 },
      yAxis: { scaleType: "linear", grid: false, min: 0, max: 100 },
      margin: { top: 20, right: 20, bottom: 45, left: 20 },
      colorScaleId: undefined,
      colorField: undefined,
      filters: [],
      xAxisLabel: "ID (ordered row)",
      yAxisLabel: "Square root of ID",
      xGridLines: 5,
      yGridLines: 5,
      xField: "ID",
      seriesField: ["Square Root"],
      seriesSettings: {
        "Square Root": {
          showPoints: false,
          pointSize: 4,
          pointOpacity: 1,
          lineWidth: 2,
          lineOpacity: 0.8,
          lineStyle: "solid",
          useRightAxis: false,
          lineColor: "#16a34a",
        },
      },
      styles: { curveType: "linear" },
      showXGrid: true,
      showYGrid: true,
      showLegend: false,
      legendPosition: "top",
    },
  ],
  calculations: [],
  gridSettings: {
    columnCount: 12,
    rowHeight: 100,
    containerPadding: 10,
    showBackgroundMarkers: true,
  },
  metadata: {
    name: "Untitled",
    version: 1,
    createdAt: "2025-03-11T02:45:21.432Z",
    modifiedAt: "2025-03-11T02:45:21.432Z",
  },
  colorScales: [],
};
