import { SavedDataStructure } from "exploreda";

export const demoSettings: SavedDataStructure = {
  charts: [
    {
      title: "2D View",
      type: "scatter",
      field: "Run ID",
      layout: { x: 9, y: 0, w: 3, h: 3 },
      xAxis: {
        scaleType: "linear",
        grid: false,
        min: 0,
        max: 100,
      },
      yAxis: {
        scaleType: "linear",
        grid: false,
        min: 0,
        max: 100,
      },
      margin: { top: 20, right: 20, bottom: 30, left: 60 },
      facet: { enabled: false, type: "wrap", rowVariable: "", columnCount: 2 },
      colorScaleId: "b9b0fa64-5d7b-4fdc-b191-daeb7920ecb3",
      colorField: "Run ID",
      xAxisLabel: "",
      yAxisLabel: "",
      xGridLines: 5,
      yGridLines: 5,
      xField: "Time",
      yField: "Z",
      filters: [],
      id: "5cc180fb-d35e-4249-a46c-cba04f13b6a8",
    },
    {
      title: "Facet by run so each is its own chart",
      type: "3d-scatter",
      field: "Run ID",
      layout: { x: 3, y: 3, w: 9, h: 7 },
      xAxis: {
        scaleType: "linear",
        grid: false,
        min: 0,
        max: 100,
        zoomLevel: 1,
      },
      yAxis: {
        scaleType: "linear",
        grid: false,
        min: 0,
        max: 100,
        zoomLevel: 1,
      },
      margin: { top: 20, right: 20, bottom: 20, left: 20 },
      facet: {
        enabled: true,
        type: "wrap",
        rowVariable: "Run ID",
        columnCount: 3,
      },
      colorScaleId: "b9b0fa64-5d7b-4fdc-b191-daeb7920ecb3",
      colorField: "Run ID",
      xAxisLabel: "",
      yAxisLabel: "",
      xGridLines: 5,
      yGridLines: 5,
      xField: "X",
      yField: "Y",
      filters: [],
      id: "be9caf07-92eb-43ad-b3d5-4d3853c259c9",
      zField: "Z",
      cameraPosition: {
        x: -17.93186528327538,
        y: 10.101726965484353,
        z: -27.491089684368024,
      },
      cameraTarget: { x: 0, y: 0, z: 0 },
      pointSize: 1,
      pointOpacity: 0.8,
      showGrid: true,
      showAxes: true,
      zAxis: {
        scaleType: "linear",
        grid: false,
        min: 0,
        max: 100,
        zoomLevel: 1,
      },
    },
    {
      title: "All Runs together, use color",
      type: "3d-scatter",
      field: "Run ID",
      layout: { x: 0, y: 3, w: 3, h: 4 },
      xAxis: {
        scaleType: "linear",
        grid: false,
        min: 0,
        max: 100,
        zoomLevel: 1,
      },
      yAxis: {
        scaleType: "linear",
        grid: false,
        min: 0,
        max: 100,
        zoomLevel: 1,
      },
      margin: { top: 20, right: 20, bottom: 20, left: 20 },
      facet: {
        enabled: false,
        type: "wrap",
        rowVariable: "Run ID",
        columnCount: 3,
      },
      colorScaleId: "b9b0fa64-5d7b-4fdc-b191-daeb7920ecb3",
      colorField: "Run ID",
      xAxisLabel: "",
      yAxisLabel: "",
      xGridLines: 5,
      yGridLines: 5,
      xField: "X",
      yField: "Y",
      filters: [],
      zField: "Z",
      cameraPosition: {
        x: -4.331613307291414,
        y: 18.460295875011493,
        z: -18.640629992563348,
      },
      cameraTarget: { x: 0, y: 0, z: 0 },
      pointSize: 0.4,
      pointOpacity: 0.8,
      showGrid: true,
      showAxes: true,
      zAxis: {
        scaleType: "linear",
        grid: false,
        min: 0,
        max: 100,
        zoomLevel: 1,
      },
      id: "63671467-96ba-49f1-87a6-5310a20e1a60",
    },
    {
      title: "",
      type: "markdown",
      field: "",
      layout: { x: 0, y: 0, w: 9, h: 4 },
      xAxis: { scaleType: "linear", grid: false, min: 0, max: 100 },
      yAxis: { scaleType: "linear", grid: false, min: 0, max: 100 },
      margin: { top: 20, right: 20, bottom: 20, left: 20 },
      facet: { enabled: false, type: "wrap", rowVariable: "", columnCount: 2 },
      xAxisLabel: "",
      yAxisLabel: "",
      xGridLines: 5,
      yGridLines: 5,
      filters: [],
      id: "0b02a715-10b4-4cc8-bd23-e59c6d54b6b7",
      colorField: "",
      colorScaleId: undefined,
      content:
        '<h1 class="heading-node">Lorenz Attractor Demo</h1><p class="text-node"><span>This shows using a 2D scatter alongside 3D scatters to show the development of several slightly different Lorenz attractors.  The 3D scatters show facetting on the </span><code class="inline" spellcheck="false">Run ID</code> or coloring on it (and putting all points together).</p><p class="text-node"><span>To have some fun:</span></p><ul class="list-node"><li><p class="text-node">Drag a box around the 2D scatter chart and watch all the 3D charts update</p></li><li><p class="text-node"><span>Drag the 3D facet to change the view, wait 1s and watch all the other 3D views synchronize!</span></p></li></ul>',
    },
  ],
  calculations: [],
  gridSettings: {
    columnCount: 12,
    rowHeight: 100,
    containerPadding: 10,
    showBackgroundMarkers: true,
  },
  metadata: {
    name: "Untitled",
    version: 1,
    createdAt: "2025-03-09T04:46:29.921Z",
    modifiedAt: "2025-03-09T04:46:29.921Z",
  },
  colorScales: [
    {
      name: "Run ID",
      type: "numerical",
      palette: "Viridis",
      min: 1,
      max: 5,
      id: "b9b0fa64-5d7b-4fdc-b191-daeb7920ecb3",
    },
    {
      name: "Time",
      type: "numerical",
      palette: "Viridis",
      min: 0,
      max: 1.99,
      id: "1b703a82-284c-4b1d-a32f-b6f2d3eb4049",
    },
  ],
};
