import { SavedDataStructure } from "exploreda";

export const nbaStatsSettings: SavedDataStructure = {
  charts: [
    {
      title: "Summary Table",
      type: "summary",
      field: "",
      layout: { x: 0, y: 0, w: 6, h: 6 },
      xAxis: { scaleType: "linear", grid: false, min: 0, max: 100 },
      yAxis: { scaleType: "linear", grid: false, min: 0, max: 100 },
      margin: { top: 20, right: 20, bottom: 20, left: 20 },
      colorScaleId: undefined,
      colorField: undefined,
      facet: { enabled: false, type: "wrap", rowVariable: "", columnCount: 2 },
      xAxisLabel: "",
      yAxisLabel: "",
      xGridLines: 5,
      yGridLines: 5,
      filters: [],
      id: "be2b8bbc-221d-4ea1-b494-6d09d6af4516",
    },
    {
      title: "Pivot Table",
      type: "pivot",
      field: "",
      layout: { x: 6, y: 0, w: 6, h: 4 },
      xAxis: { scaleType: "linear", grid: false, min: 0, max: 100 },
      yAxis: { scaleType: "linear", grid: false, min: 0, max: 100 },
      colorScaleId: undefined,
      colorField: undefined,
      margin: { top: 20, right: 20, bottom: 20, left: 20 },
      facet: { enabled: false, type: "wrap", rowVariable: "", columnCount: 2 },
      xAxisLabel: "",
      yAxisLabel: "",
      xGridLines: 5,
      yGridLines: 5,
      filters: [],
      id: "75dc0719-4791-41cf-ac0f-3b13a1ffd622",
      rowFields: ["Team"],
      columnField: "",
      valueFields: [{ field: "STL", aggregation: "max" }],
    },
    {
      title: "Scatter Plot",
      type: "scatter",
      field: "",
      layout: { x: 6, y: 4, w: 6, h: 4 },
      xAxis: { scaleType: "linear", grid: false, min: 0, max: 100 },
      yAxis: { scaleType: "linear", grid: false, min: 0, max: 100 },
      margin: { top: 20, right: 20, bottom: 20, left: 20 },
      facet: { enabled: false, type: "wrap", rowVariable: "", columnCount: 2 },
      colorScaleId: "4f3d01de-a3e2-41c5-aaeb-2c1bdf2a4fb0",
      colorField: "Pos",
      xAxisLabel: "Points",
      yAxisLabel: "Assists",
      xGridLines: 5,
      yGridLines: 5,
      filters: [],
      id: "d5d863d5-292d-46c5-a85b-b3cff0a14f19",
      xField: "PTS",
      yField: "AST",
    },
    {
      id: "a446cf58-2839-4497-afa0-73782bc573ec",
      type: "color-legend",
      title: "Color Legend",
      field: "",
      layout: { x: 0, y: 6, w: 6, h: 2 },
      facet: {
        enabled: false,
        type: "grid",
        rowVariable: "",
        columnVariable: "",
      },
      xAxis: { scaleType: "linear", grid: false, min: 0, max: 100 },
      yAxis: { scaleType: "linear", grid: false, min: 0, max: 100 },
      colorScaleId: undefined,
      colorField: undefined,
      margin: { top: 20, right: 20, bottom: 20, left: 20 },
      filters: [],
      xAxisLabel: "",
      yAxisLabel: "",
      xGridLines: 0,
      yGridLines: 0,
      fields: ["Pos"],
      numericalBreakpoints: 5,
      wrap: false,
    },
    {
      title: "Data Table",
      type: "data-table",
      field: "",
      layout: { x: 6, y: 8, w: 6, h: 4 },
      xAxis: { scaleType: "linear", grid: false, min: 0, max: 100 },
      yAxis: { scaleType: "linear", grid: false, min: 0, max: 100 },
      margin: { top: 20, right: 20, bottom: 20, left: 20 },
      facet: { enabled: false, type: "wrap", rowVariable: "", columnCount: 2 },
      xAxisLabel: "",
      yAxisLabel: "",
      xGridLines: 5,
      yGridLines: 5,
      filters: [],
      id: "5b8ad128-7291-40da-b929-2cf7ad16da18",
      columns: [
        { id: "Team", field: "Team" },
        { id: "Player", field: "Player" },
        { id: "Pos", field: "Pos" },
      ],
      pageSize: 25,
      currentPage: 1,
      sortDirection: "asc",
      globalSearch: "",
      tableHeight: 400,
      colorScaleId: undefined,
      colorField: undefined,
    },
  ],
  calculations: [],
  gridSettings: {
    columnCount: 12,
    rowHeight: 100,
    containerPadding: 10,
    showBackgroundMarkers: true,
  },
  metadata: {
    name: "Untitled",
    version: 1,
    createdAt: "2025-03-12T04:08:53.067Z",
    modifiedAt: "2025-03-12T04:08:53.067Z",
  },
  colorScales: [
    {
      name: "Team",
      type: "categorical",
      palette: [
        "#1f77b4",
        "#ff7f0e",
        "#2ca02c",
        "#d62728",
        "#9467bd",
        "#8c564b",
        "#e377c2",
        "#7f7f7f",
        "#bcbd22",
        "#17becf",
        "#1f77b4",
        "#ff7f0e",
        "#2ca02c",
        "#d62728",
        "#9467bd",
        "#8c564b",
        "#e377c2",
        "#7f7f7f",
        "#bcbd22",
        "#17becf",
        "#1f77b4",
        "#ff7f0e",
        "#2ca02c",
        "#d62728",
        "#9467bd",
        "#8c564b",
        "#e377c2",
        "#7f7f7f",
        "#bcbd22",
        "#17becf",
        "#1f77b4",
        "#ff7f0e",
      ],
      mapping: [
        ["DAL", "#1f77b4"],
        ["OKC", "#ff7f0e"],
        ["MIL", "#2ca02c"],
        ["NYK", "#d62728"],
        ["DEN", "#9467bd"],
        ["MIN", "#8c564b"],
        ["PHO", "#e377c2"],
        ["BOS", "#7f7f7f"],
        ["SAC", "#bcbd22"],
        ["GSW", "#17becf"],
        ["CHI", "#1f77b4"],
        ["LAL", "#ff7f0e"],
        ["PHI", "#2ca02c"],
        ["ORL", "#d62728"],
        ["ATL", "#9467bd"],
        ["2TM", "#8c564b"],
        ["TOR", "#e377c2"],
        ["IND", "#7f7f7f"],
        ["LAC", "#bcbd22"],
        ["HOU", "#17becf"],
        ["BRK", "#1f77b4"],
        ["NOP", "#ff7f0e"],
        ["WAS", "#2ca02c"],
        ["SAS", "#d62728"],
        ["MEM", "#9467bd"],
        ["CLE", "#8c564b"],
        ["UTA", "#e377c2"],
        ["CHO", "#7f7f7f"],
        ["DET", "#bcbd22"],
        ["MIA", "#17becf"],
        ["POR", "#1f77b4"],
        ["3TM", "#ff7f0e"],
      ],
      id: "286917e0-3d87-455b-b3b4-041016a1109c",
    },
    {
      name: "Pos",
      type: "categorical",
      palette: ["#1f77b4", "#ff7f0e", "#2ca02c", "#d62728", "#9467bd"],
      mapping: [
        ["PG", "#1f77b4"],
        ["PF", "#ff7f0e"],
        ["C", "#2ca02c"],
        ["SG", "#d62728"],
        ["SF", "#9467bd"],
      ],
      id: "4f3d01de-a3e2-41c5-aaeb-2c1bdf2a4fb0",
    },
  ],
};
