import { SavedDataStructure } from "exploreda";

const axes = {
  xAxis: { scaleType: "linear", grid: false, min: 0, max: 100 },
  yAxis: { scaleType: "linear", grid: false, min: 0, max: 100 },
} as const;
const noFacet = {
  enabled: false,
  type: "wrap",
  rowVariable: "",
  columnCount: 2,
} as const;
const positionScaleId = "4f3d01de-a3e2-41c5-aaeb-2c1bdf2a4fb0";

export const nbaStatsSettings: SavedDataStructure = {
  charts: [
    {
      title: "Season fields",
      type: "summary",
      field: "",
      layout: { x: 0, y: 0, w: 5, h: 7 },
      ...axes,
      margin: { top: 20, right: 20, bottom: 20, left: 20 },
      colorScaleId: undefined,
      colorField: undefined,
      facet: noFacet,
      xAxisLabel: "",
      yAxisLabel: "",
      xGridLines: 5,
      yGridLines: 5,
      filters: [],
      id: "be2b8bbc-221d-4ea1-b494-6d09d6af4516",
    },
    {
      title: "Who scores, and who sets up teammates?",
      type: "scatter",
      field: "",
      layout: { x: 5, y: 0, w: 7, h: 5 },
      ...axes,
      margin: { top: 20, right: 20, bottom: 45, left: 60 },
      facet: noFacet,
      colorScaleId: positionScaleId,
      colorField: "Pos",
      xAxisLabel: "Points (season total)",
      yAxisLabel: "Assists (season total)",
      xGridLines: 5,
      yGridLines: 5,
      filters: [],
      id: "d5d863d5-292d-46c5-a85b-b3cff0a14f19",
      xField: "PTS",
      yField: "AST",
    },
    {
      id: "a446cf58-2839-4497-afa0-73782bc573ec",
      type: "color-legend",
      title: "Positions",
      field: "",
      layout: { x: 5, y: 5, w: 7, h: 2 },
      facet: {
        enabled: false,
        type: "grid",
        rowVariable: "",
        columnVariable: "",
      },
      ...axes,
      colorField: undefined,
      margin: { top: 20, right: 20, bottom: 20, left: 20 },
      filters: [],
      xAxisLabel: "",
      yAxisLabel: "",
      xGridLines: 0,
      yGridLines: 0,
      fields: ["Pos"],
      colorScaleId: positionScaleId,
      numericalBreakpoints: 5,
      wrap: false,
    },
    {
      title: "What does a typical season look like at each position?",
      type: "pivot",
      field: "",
      layout: { x: 5, y: 7, w: 7, h: 3 },
      ...axes,
      colorScaleId: undefined,
      colorField: undefined,
      margin: { top: 20, right: 20, bottom: 20, left: 20 },
      facet: noFacet,
      xAxisLabel: "",
      yAxisLabel: "",
      xGridLines: 5,
      yGridLines: 5,
      filters: [],
      id: "75dc0719-4791-41cf-ac0f-3b13a1ffd622",
      rowFields: ["Pos"],
      columnField: "",
      valueFields: [
        { field: "Player", aggregation: "count", label: "Rows" },
        { field: "PTS", aggregation: "median", label: "Median points" },
        { field: "AST", aggregation: "median", label: "Median assists" },
        { field: "TRB", aggregation: "median", label: "Median rebounds" },
      ],
    },
    {
      title: "Season scoring leaders",
      type: "data-table",
      field: "",
      layout: { x: 0, y: 7, w: 5, h: 6 },
      ...axes,
      margin: { top: 20, right: 20, bottom: 20, left: 20 },
      facet: noFacet,
      xAxisLabel: "",
      yAxisLabel: "",
      xGridLines: 5,
      yGridLines: 5,
      filters: [],
      id: "5b8ad128-7291-40da-b929-2cf7ad16da18",
      columns: [
        { id: "Player", field: "Player", width: 146 },
        { id: "Team", field: "Team", width: 66 },
        { id: "Pos", field: "Pos", width: 58 },
        { id: "PTS", field: "PTS", width: 78 },
        { id: "AST", field: "AST", width: 66 },
        { id: "TRB", field: "TRB", width: 66 },
      ],
      sortBy: "PTS",
      sortDirection: "desc",
      globalSearch: "",
      colorScaleId: undefined,
      colorField: undefined,
    },
  ],
  calculations: [],
  gridSettings: {
    columnCount: 12,
    rowHeight: 100,
    containerPadding: 10,
    showBackgroundMarkers: false,
  },
  metadata: {
    name: "NBA season",
    version: 1,
    createdAt: "2025-03-12T04:08:53.067Z",
    modifiedAt: "2026-09-28T00:00:00.000Z",
  },
  colorScales: [
    {
      name: "Pos",
      sourceField: "Pos",
      type: "categorical",
      palette: ["#1f77b4", "#ff7f0e", "#2ca02c", "#d62728", "#9467bd"],
      mapping: [
        ["PG", "#1f77b4"],
        ["SG", "#d62728"],
        ["SF", "#9467bd"],
        ["PF", "#ff7f0e"],
        ["C", "#2ca02c"],
      ],
      id: positionScaleId,
    },
  ],
};
