import { SavedDataStructure } from "exploreda";

export const worldBankPopulationSettings: SavedDataStructure = {
  charts: [
    {
      id: "50f9d52c-fc0f-4a4d-8bee-561b1699fc05",
      type: "line",
      title: "",
      field: "",
      layout: { x: 0, y: 0, w: 12, h: 90 },
      facet: {
        enabled: true,
        type: "wrap",
        rowVariable: "Country Name",
        columnCount: 4,
      },
      xAxis: { scaleType: "linear", grid: false, min: 0, max: 100 },
      yAxis: { scaleType: "linear", grid: false, min: 0, max: 100 },
      margin: { top: 20, right: 20, bottom: 20, left: 20 },
      filters: [],
      xAxisLabel: "",
      yAxisLabel: "",
      xGridLines: 5,
      yGridLines: 5,
      xField: "year",
      seriesField: ["value"],
      seriesSettings: {
        value: {
          showPoints: false,
          pointSize: 4,
          pointOpacity: 1,
          lineWidth: 2,
          lineOpacity: 0.8,
          lineStyle: "solid",
          useRightAxis: false,
          lineColor: "#2563eb",
        },
      },
      styles: { curveType: "linear" },
      showXGrid: true,
      showYGrid: true,
      showLegend: false,
      legendPosition: "top",
    },
  ],
  calculations: [],
  gridSettings: {
    columnCount: 12,
    rowHeight: 100,
    containerPadding: 10,
    showBackgroundMarkers: true,
  },
  metadata: {
    name: "Untitled",
    version: 1,
    createdAt: "2025-03-12T03:54:55.605Z",
    modifiedAt: "2025-03-12T03:54:55.605Z",
  },
  colorScales: [],
};
