// Generated by apps/data-samples/prepare/beijing.ts. Do not edit.
export const facts = {
  "audit": {
    "stations": 12,
    "days": 366,
    "stationDays": 4392,
    "expectedStationDays": 4392,
    "sourceHours": 105408,
    "expectedHours": 105408,
    "duplicateHours": 0,
    "daysWithNoRecords": 0,
    "qualifiedPm25Days": 4275,
    "pm25ValidHours": 103151,
    "referenceStation": "Aotizhongxin",
    "referenceQualifiedDays": 358
  },
  "findings": {
    "highOzone": {
      "threshold": 81.9,
      "days": 1057,
      "medianPm25": 65.5,
      "medianPm25AllDays": 54.1,
      "r": -0.22
    },
    "pm25CoveragePct": 97.9,
    "lowestCoverage": {
      "station": "Dongsi",
      "month": "07 Jul",
      "pct": 82.8
    },
    "medianPm25": {
      "Winter": 43.9,
      "Spring": 54.6,
      "Summer": 55,
      "Autumn": 67
    },
    "medianO3": {
      "Winter": 30.3,
      "Summer": 94.3
    },
    "pm25No2": {
      "n": 4235,
      "r": 0.76
    },
    "tempO3": {
      "Winter": {
        "n": 1083,
        "r": 0.01
      },
      "Spring": {
        "n": 1085,
        "r": 0.71
      },
      "Summer": {
        "n": 1068,
        "r": 0.34
      },
      "Autumn": {
        "n": 1021,
        "r": 0.6
      }
    },
    "worstDay": {
      "station": "Gucheng",
      "date": "2016-12-20",
      "pm25": 476.3
    },
    "completeSixPollutantDays": 4143
  }
} as const;
