// Generated by apps/data-samples/prepare/earthquakes.ts. Do not edit.
export const facts = {
  "audit": {
    "query": "https://earthquake.usgs.gov/fdsnws/event/1/query?format=csv&starttime=2023-01-01&endtime=2024-01-01&minmagnitude=4.5&eventtype=earthquake&orderby=time-asc",
    "retrieved": "2026-10-07T04:08:56.936Z",
    "sourceRows": 7643,
    "events": 7643,
    "outsideWindow": 0,
    "duplicateIds": 0,
    "mappable": 7643,
    "finiteDepthAndMag": 7643,
    "belowMinimum": 0
  },
  "findings": {
    "busiestDay": {
      "date": "2023-12-02",
      "events": 164
    },
    "medianPerDay": 18,
    "quietDays": 0,
    "depthBands": {
      "1 Shallow, under 70 km": 6060,
      "2 Intermediate, 70–300 km": 1249,
      "3 Deep, 300 km or more": 334
    },
    "topAreas": [
      {
        "name": "Philippines",
        "events": 793
      },
      {
        "name": "Indonesia",
        "events": 760
      },
      {
        "name": "Papua New Guinea",
        "events": 378
      }
    ],
    "strongest": {
      "id": "us6000jllz",
      "mag": 7.8,
      "place": "Pazarcik earthquake, Kahramanmaras earthquake sequence",
      "date": "2023-02-06"
    },
    "commonMagType": {
      "type": "mb",
      "events": 6150
    },
    "magTypes": 9,
    "medianMagCommonType": {
      "shallow": 4.6,
      "intermediate": 4.6,
      "deep": 4.6
    },
    "usShare": 99.3,
    "lowMetadata": 30,
    "networks": 8
  }
} as const;
