// Generated by apps/data-samples/prepare/flights.ts. Do not edit.
export const facts = {
  "audit": {
    "flights": 27004,
    "uniqueFlightIds": 27004,
    "finiteDepDelay": 26483,
    "finiteArrDelay": 26398,
    "pairedDelays": 26398,
    "distanceSum": 27188805,
    "operatingDays": 31,
    "lookups": {
      "airlines": {
        "matched": 27004,
        "duplicateKeys": []
      },
      "planes": {
        "missingTailnum": 155,
        "matched": 22525,
        "unmatched": 4324,
        "duplicateKeys": []
      },
      "weather": {
        "matched": 26952,
        "unmatched": 52,
        "ambiguous": 0,
        "duplicateKeys": []
      }
    }
  },
  "findings": {
    "morning": {
      "hours": "5–9",
      "flights": 7875,
      "meanDepDelay": 4.5
    },
    "evening": {
      "hours": "17–21",
      "flights": 7433,
      "meanDepDelay": 16.4
    },
    "bandCounts": {
      "Up to 15 min": 4744,
      "On time or early": 16821,
      "15–60 min": 3097,
      "Over 60 min": 1821,
      "Not recorded": 521
    },
    "overHourDepartures": 1821,
    "overHourStillOverHour": 1569,
    "lateDeparturesArrivingOnTime": 2537,
    "lateDeparturesWithArrival": 9620,
    "delayCorrelation": 0.916,
    "medianDepDelay": -2,
    "meanDepDelay": 10,
    "worstDays": [
      {
        "date": "2013-01-31",
        "mean": 28.7,
        "flights": 843
      },
      {
        "date": "2013-01-30",
        "mean": 28.6,
        "flights": 802
      },
      {
        "date": "2013-01-16",
        "mean": 24.6,
        "flights": 855
      }
    ],
    "bestDay": {
      "date": "2013-01-15",
      "mean": 0.1,
      "flights": 881
    },
    "lowVisibility": {
      "flights": 1852,
      "meanDepDelay": 17.1
    },
    "clearVisibility": {
      "flights": 20257,
      "meanDepDelay": 9.2
    }
  }
} as const;
