// Generated by apps/data-samples/prepare/wine.ts. Do not edit.
export const facts = {
  "wines": 1599,
  "bandCounts": {
    "Ordinary (3–5)": 744,
    "Good (6)": 638,
    "Excellent (7–8)": 217
  },
  "medianAlcohol": {
    "Ordinary (3–5)": 9.7,
    "Good (6)": 10.5,
    "Excellent (7–8)": 11.6
  },
  "medianVolatileAcidity": {
    "Ordinary (3–5)": 0.59,
    "Good (6)": 0.49,
    "Excellent (7–8)": 0.37
  },
  "medianSulphates": {
    "Ordinary (3–5)": 0.58,
    "Good (6)": 0.64,
    "Excellent (7–8)": 0.74
  },
  "alcoholDensityR": -0.5,
  "alcoholQualityR": 0.48,
  "volatileQualityR": -0.39
} as const;
