// Generated by apps/data-samples/prepare/worldbank.ts. Do not edit.
export const facts = {
  "audit": {
    "vintage": "2026-07-13",
    "economies": 217,
    "aggregatesExcluded": 79,
    "baseRows": 5208,
    "baseNullPopulation": 0,
    "duplicateKeys": 0,
    "population2000": 6139355967,
    "population2023": 8039550134,
    "gdp": {
      "rows": 4721,
      "matchedBase": 4721,
      "lookupOnly": 0
    },
    "life": {
      "rows": 5208,
      "matchedBase": 5208,
      "lookupOnly": 0
    },
    "electricity": {
      "rows": 5135,
      "matchedBase": 5135,
      "lookupOnly": 0
    },
    "endpointCohort": 211,
    "countriesWithCoordinates": 211
  },
  "findings": {
    "incomeLongevity": {
      "countries": 197,
      "r": 0.86
    },
    "medianAccess": {
      "start": 96.7,
      "end": 100,
      "countries": 211
    },
    "universalAccess": {
      "start": 77,
      "end": 138
    },
    "withoutElectricity": {
      "millions": 675,
      "weightedAccessPct": 91.6,
      "meanCountryAccessPct": 88.2,
      "topRegion": {
        "region": "Sub-Saharan Africa",
        "millions": 588
      },
      "topCountries": [
        {
          "name": "Nigeria",
          "millions": 88,
          "pct": 61.2
        },
        {
          "name": "Congo, Dem. Rep.",
          "millions": 82,
          "pct": 22.1
        },
        {
          "name": "Ethiopia",
          "millions": 57,
          "pct": 55.4
        }
      ]
    },
    "gains": {
      "lowStartCountries": 52,
      "lowStartMedianGain": 35.7,
      "highStartMedianGain": 0.7
    }
  }
} as const;
