import type { FieldSettings } from "@/lib/fieldSettings";
import type {
  SavedCalculation,
  SavedDataStructure,
} from "@/types/SavedDataStructure";
import type {
  GridSettings,
  SavedChartSettings,
  ViewMetadata,
} from "@/types/SavedDataTypes";

/**
 * How dashboard text carries one saved setting: the text that writes it, or
 * why it is deliberately left out. Each map below is a `Record` over every
 * key of its type, so a new setting fails to compile until it is mapped or
 * excluded here on purpose.
 */
export type DslCoverage = { text: string } | { excluded: string };

type ChartType = SavedChartSettings["type"];
type SettingKey<T extends ChartType> = Exclude<
  keyof Extract<SavedChartSettings, { type: T }>,
  "id" | "type"
> &
  string;

/**
 * Lists every key, and fails to compile when a chart type gains a setting
 * that is missing here, so text coverage can never silently fall behind.
 */
function keys<T extends ChartType>() {
  return <const K extends readonly SettingKey<T>[]>(
    list: K &
      ([SettingKey<T>] extends [K[number]]
        ? unknown
        : { missing: Exclude<SettingKey<T>, K[number]> })
  ): readonly string[] => list;
}

/** Every saved setting of every chart type, reachable as a text path. */
export const CHART_SETTING_KEYS: Record<ChartType, readonly string[]> = {
  row: keys<"row">()([
    "colorField",
    "colorScaleId",
    "facet",
    "field",
    "filters",
    "layout",
    "localFilters",
    "margin",
    "maxRowHeight",
    "minRowHeight",
    "note",
    "style",
    "subtitle",
    "title",
    "xAxis",
    "xAxisLabel",
    "xGridLines",
    "yAxis",
    "yAxisLabel",
    "yGridLines",
  ]),
  bar: keys<"bar">()([
    "aggregateId",
    "binCount",
    "colorField",
    "colorScaleId",
    "facet",
    "field",
    "filters",
    "forceString",
    "layout",
    "localFilters",
    "margin",
    "seriesField",
    "seriesLayout",
    "note",
    "style",
    "subtitle",
    "title",
    "xAxis",
    "xAxisLabel",
    "xGridLines",
    "yAxis",
    "yAxisLabel",
    "yGridLines",
  ]),
  scatter: keys<"scatter">()([
    "colorField",
    "colorScaleId",
    "contour",
    "density",
    "display",
    "facet",
    "field",
    "filters",
    "hexbin",
    "layout",
    "localFilters",
    "margin",
    "marginals",
    "maxBubbleRadius",
    "pointOpacity",
    "pointSize",
    "regression",
    "sizeField",
    "summary",
    "note",
    "style",
    "subtitle",
    "title",
    "xAxis",
    "xAxisLabel",
    "xField",
    "xGridLines",
    "yAxis",
    "yAxisLabel",
    "yField",
    "yGridLines",
  ]),
  pivot: keys<"pivot">()([
    "colorField",
    "colorScaleId",
    "columnField",
    "facet",
    "field",
    "filters",
    "layout",
    "localFilters",
    "margin",
    "rowFields",
    "shadeCells",
    "showTotals",
    "note",
    "style",
    "subtitle",
    "title",
    "valueFields",
    "xAxis",
    "xAxisLabel",
    "xGridLines",
    "yAxis",
    "yAxisLabel",
    "yGridLines",
  ]),
  summary: keys<"summary">()([
    "colorField",
    "colorScaleId",
    "facet",
    "field",
    "filters",
    "layout",
    "localFilters",
    "margin",
    "note",
    "style",
    "subtitle",
    "title",
    "xAxis",
    "xAxisLabel",
    "xGridLines",
    "yAxis",
    "yAxisLabel",
    "yGridLines",
  ]),
  "data-table": keys<"data-table">()([
    "colorField",
    "colorScaleId",
    "columns",
    "facet",
    "field",
    "filters",
    "globalSearch",
    "layout",
    "localFilters",
    "margin",
    "showDistributions",
    "sortBy",
    "sortDirection",
    "note",
    "style",
    "subtitle",
    "title",
    "xAxis",
    "xAxisLabel",
    "xGridLines",
    "yAxis",
    "yAxisLabel",
    "yGridLines",
  ]),
  markdown: keys<"markdown">()([
    "colorField",
    "colorScaleId",
    "content",
    "facet",
    "field",
    "filters",
    "layout",
    "localFilters",
    "margin",
    "note",
    "style",
    "subtitle",
    "title",
    "xAxis",
    "xAxisLabel",
    "xGridLines",
    "yAxis",
    "yAxisLabel",
    "yGridLines",
  ]),
  boxplot: keys<"boxplot">()([
    "autoBandwidth",
    "colorField",
    "colorScaleId",
    "facet",
    "field",
    "filters",
    "layout",
    "localFilters",
    "margin",
    "showObservations",
    "showOutliers",
    "sortBy",
    "styles",
    "note",
    "style",
    "subtitle",
    "title",
    "violinBandwidth",
    "violinOverlay",
    "whiskerType",
    "xAxis",
    "xAxisLabel",
    "xGridLines",
    "yAxis",
    "yAxisLabel",
    "yGridLines",
  ]),
  line: keys<"line">()([
    "colorField",
    "colorScaleId",
    "facet",
    "field",
    "filters",
    "layout",
    "legendPosition",
    "localFilters",
    "margin",
    "seriesField",
    "seriesSettings",
    "showLegend",
    "showXGrid",
    "showYGrid",
    "styles",
    "time",
    "note",
    "style",
    "subtitle",
    "title",
    "xAxis",
    "xAxisLabel",
    "xField",
    "xGridLines",
    "yAxis",
    "yAxisLabel",
    "yGridLines",
  ]),
  sankey: keys<"sankey">()([
    "aggregation",
    "colorField",
    "colorScaleId",
    "facet",
    "field",
    "filters",
    "flowColor",
    "layout",
    "localFilters",
    "margin",
    "maxNodesPerStage",
    "measureField",
    "missingStages",
    "nodeOrder",
    "stages",
    "note",
    "style",
    "subtitle",
    "title",
    "xAxis",
    "xAxisLabel",
    "xGridLines",
    "yAxis",
    "yAxisLabel",
    "yGridLines",
  ]),
  "parallel-coordinates": keys<"parallel-coordinates">()([
    "axes",
    "colorField",
    "colorScaleId",
    "facet",
    "field",
    "filters",
    "layout",
    "lineOpacity",
    "lineWidth",
    "localFilters",
    "margin",
    "note",
    "style",
    "subtitle",
    "title",
    "xAxis",
    "xAxisLabel",
    "xGridLines",
    "yAxis",
    "yAxisLabel",
    "yGridLines",
  ]),
  calendar: keys<"calendar">()([
    "aggregation",
    "colorField",
    "colorScaleId",
    "facet",
    "field",
    "filters",
    "layout",
    "localFilters",
    "margin",
    "measureField",
    "note",
    "style",
    "subtitle",
    "title",
    "weekStart",
    "xAxis",
    "xAxisLabel",
    "xGridLines",
    "yAxis",
    "yAxisLabel",
    "yGridLines",
    "year",
  ]),
  heatmap: keys<"heatmap">()([
    "aggregation",
    "colorField",
    "colorScaleId",
    "columnField",
    "facet",
    "field",
    "filters",
    "layout",
    "localFilters",
    "margin",
    "maxCategories",
    "measureField",
    "showValues",
    "sortBy",
    "note",
    "style",
    "subtitle",
    "title",
    "xAxis",
    "xAxisLabel",
    "xGridLines",
    "yAxis",
    "yAxisLabel",
    "yGridLines",
  ]),
  ecdf: keys<"ecdf">()([
    "colorField",
    "colorScaleId",
    "direction",
    "facet",
    "field",
    "filters",
    "layout",
    "localFilters",
    "logX",
    "margin",
    "showOverall",
    "showQuantiles",
    "note",
    "style",
    "subtitle",
    "title",
    "xAxis",
    "xAxisLabel",
    "xGridLines",
    "yAxis",
    "yAxisLabel",
    "yGridLines",
  ]),
  map: keys<"map">()([
    "aggregation",
    "colorField",
    "colorScaleId",
    "facet",
    "featureKey",
    "field",
    "filters",
    "geometryAssetId",
    "labelField",
    "latitudeField",
    "layout",
    "localFilters",
    "longitudeField",
    "margin",
    "measureField",
    "mode",
    "outlineWidth",
    "pointOpacity",
    "pointRadius",
    "projection",
    "regionField",
    "showRegionLabels",
    "sizeField",
    "note",
    "style",
    "subtitle",
    "title",
    "view",
    "xAxis",
    "xAxisLabel",
    "xGridLines",
    "yAxis",
    "yAxisLabel",
    "yGridLines",
  ]),
  "metric-card": keys<"metric-card">()([
    "aggregation",
    "colorField",
    "colorScaleId",
    "entityField",
    "facet",
    "field",
    "filters",
    "layout",
    "localFilters",
    "margin",
    "measureField",
    "note",
    "style",
    "subtitle",
    "title",
    "xAxis",
    "xAxisLabel",
    "xGridLines",
    "yAxis",
    "yAxisLabel",
    "yGridLines",
  ]),
  "color-legend": keys<"color-legend">()([
    "colorField",
    "colorScaleId",
    "facet",
    "field",
    "fields",
    "filters",
    "layout",
    "localFilters",
    "margin",
    "numericalBreakpoints",
    "note",
    "style",
    "subtitle",
    "title",
    "wrap",
    "xAxis",
    "xAxisLabel",
    "xGridLines",
    "yAxis",
    "yAxisLabel",
    "yGridLines",
  ]),
  "3d-scatter": keys<"3d-scatter">()([
    "cameraPosition",
    "cameraTarget",
    "colorField",
    "colorScaleId",
    "facet",
    "field",
    "filters",
    "layout",
    "localFilters",
    "margin",
    "pointOpacity",
    "pointSize",
    "showAxes",
    "showGrid",
    "sizeField",
    "note",
    "style",
    "subtitle",
    "title",
    "xAxis",
    "xAxisLabel",
    "xField",
    "xGridLines",
    "yAxis",
    "yAxisLabel",
    "yField",
    "yGridLines",
    "zAxis",
    "zField",
  ]),
};

/** Grid settings and the `grid` word that writes each, with its default. */
export const GRID_SETTING_WORDS: Record<
  keyof GridSettings,
  { word: string; fallback: number | boolean }
> = {
  columnCount: { word: "columns", fallback: 12 },
  rowHeight: { word: "rowHeight", fallback: 100 },
  containerPadding: { word: "padding", fallback: 10 },
  showBackgroundMarkers: { word: "markers", fallback: true },
};

/** Field display settings and the key that writes each on a field line. */
export const FIELD_SETTING_WORDS: Record<keyof FieldSettings, string> = {
  type: "as",
  label: "label",
  description: "description",
  format: "format",
  precision: "precision",
  unit: "unit",
  currency: "currency",
  datePreset: "datePreset",
  nullTokens: "nullTokens[]",
};

/** Every part of a saved dashboard, and the declaration that carries it. */
export const DASHBOARD_COVERAGE: Record<keyof SavedDataStructure, DslCoverage> =
  {
    metadata: { text: "dashboard name=" },
    gridSettings: { text: "grid" },
    fieldSettings: { text: "field, or settings after an alias or calc" },
    calculations: { text: "calc" },
    colorScales: { text: "scale @id, any setting as a path" },
    aggregates: { text: "group @id, any setting as a path" },
    rowsSettings: { text: "rows, any setting as a path" },
    charts: { text: "a chart line, any setting as a path" },
    theme: { text: "theme name=" },
    geometryAssets: {
      excluded:
        "Map shapes are data, not settings. The host passes them to the compiler, and charts refer to them by geometryAssetId.",
    },
  };

export const METADATA_COVERAGE: Record<keyof ViewMetadata, DslCoverage> = {
  name: { text: "dashboard name=" },
  version: { excluded: "The save format version, set when saving." },
  createdAt: { excluded: "A timestamp, set when saving." },
  modifiedAt: { excluded: "A timestamp, set when saving." },
};

export const CALCULATION_COVERAGE: Record<keyof SavedCalculation, DslCoverage> =
  {
    resultColumnName: { text: "calc <name>=" },
    expression: { text: "calc name=<formula>" },
  };
